apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
  namespace: developers-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
        - name: node-hello-world
          image: imtiazmasrur/node-hello-world:latest # image we have pushed to
          #   imagePullPolicy: Always # See: (Image pull policy options) https://www.airplane.dev/blog/kubernetes-image-pull-policy
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-world
  namespace: developers-space
spec:
  selector:
    app: node-hello-world
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
